#if !canImport(ObjectiveC)
import XCTest

extension HdrHistogramTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HdrHistogramTests = [
        ("testEmptyHistogram", testEmptyHistogram),
        ("testRecordValue", testRecordValue),
        ("testValueAtPercentileMatchesPercentile", testValueAtPercentileMatchesPercentile),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HdrHistogramTests.__allTests__HdrHistogramTests),
    ]
}
#endif
